### ISSUE TITLE
Generador de menú no considera las clases de elemento ul

### ISSUE THREAD

**Issue by alvaroveliz** [alvaroveliz/juanito#16]
## Descripción 

Cuando se agrega un menú usando `data-menu=""`, se busca por un elemento `ul`. 
Si dicho elemento `ul` tiene atributos, estos no son considerados en la creación del menú.

Para esto se deben agregar el soporte a la función [wp_nav_menu](http://codex.wordpress.org/Function_Reference/wp_nav_menu) considerando los siguientes parámetros:

```php
$defaults = array(
	'theme_location'  => '',
	'menu'            => '',
	'container'       => 'div',
	'container_class' => '',
	'container_id'    => '',
	'menu_class'      => 'menu',
	'menu_id'         => '',
);

wp_nav_menu( $defaults );
```

Estos parámetros deben ser completados por el `parser` automáticamente, sólo si es necesario.

## Ejemplo

Asumamos un menu sin `header` y que está dentro de un contenedor.

```html
<div id="menu" class="menu_container menu_mobile" data-menu="main">
    <ul id="menu_ul" class="menu_horizontal menu_collapsed">
        <li>...</li>
     </ul>
</div>
```

El resultado en php debería ser:

```php
$defaults = array(
	'theme_location'  => 'main',
	'menu'            => 'main',
	'container'       => 'div',
	'container_class' => 'menu_container menu_mobile',
	'container_id'    => 'menu',
	'menu_class'      => 'menu_horizontal menu_collapsed',
	'menu_id'         => 'menu_ul',
);

wp_nav_menu( $defaults );
```

**Comment by jpsepulvedaf** [comment]
Implementado en revisión [5213f90].

**Comment by alvaroveliz** [comment]
Ahora hay que subirlo a master no más!

**Comment by jpsepulvedaf** [comment]
Subido a master en revisión [dd424d4].

**Comment by alvaroveliz** [comment]
Done!
